[package]
name = "grails"
version = "0.1.0"

[dependencies]
alexandria_storage = { git = "https://github.com/keep-starknet-strange/alexandria.git" }
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git" }
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry" }
starknet = ">=2.5.3"

[[target.starknet-contract]]
casm = true

[[tool.snforge.fork]]
name = "goerli"
url = "https://starknet-testnet.blastapi.io/cc0d991d-bd8f-45ac-89c3-823291e558b4/rpc/v0_6"
block_id.tag = "Latest"
